# Generated by Django 4.1.2 on 2022-10-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='sku',
        ),
        migrations.AlterField(
            model_name='articulo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
