# Generated by Django 4.1.2 on 2022-10-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_remove_articulo_sku_alter_articulo_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
