# Generated by Django 4.1.2 on 2022-10-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimiento',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
