# Generated by Django 4.1.2 on 2022-10-14 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requerimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentario',
            name='requerimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_requerimiento', to='requerimientos.requerimiento'),
        ),
    ]
