# Generated by Django 4.1.2 on 2022-10-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimiento',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
