# Generated by Django 4.1.2 on 2022-10-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0003_alter_requerimiento_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimiento',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
