# Generated by Django 4.1.2 on 2022-10-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0004_alter_requerimiento_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimiento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
