# Generated by Django 4.1.2 on 2022-10-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='uuid_tarjeta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
